.sbtopts
Since JVM Options like `-Xmx4096m` in `.sbtopts` requires `-J` prefix as documented below, please let me correct it.
Reference: sbt-launcher-script reference about `.sbtopts`.
https://github.com/sbt/sbt-launcher-package/blob/a80410996f368937e94161227fa9ecdad0f363e5/README.md
Actually `sbt` command without `-J` prefix on JVM Options in `.sbtopts` shows following warning and doesn't start sbt.
> [warn] The `-` command is deprecated in favor of `onFailure` and will be removed in 0.14.0
=> add -J prefix for JVM options in .sbtopts

fastparse/shared/src/main/scala/fastparse/package.scala, fastparse/shared/src/main/scala/fastparse/parsers/Terminals.scala, fastparse/shared/src/test/scala/fastparse/ParsingTests.scala
Matches a string ignoring character case.
Example: 
```scala
import fastparse._
val parser = P(IgnoreCase("keyword ").rep)
val Result.Success(value, successIndex) = parser.parse("keyword Keyword keyWord ")
assert(value == (), successIndex == 24)
```
=> LiteralIgnoreCase - match a string ignoring character case

build.sbt
The utest dependency doesn't get pulled when out of tests, this way.
=> Restrained utest dependency to test scope

fastparse/shared/src/test/scala/fastparse/ExampleTests.scala, readme/Readme.scalatex
This ought to document the use of `NoCut` to enable better composition of independently written parsers.  ("Ought to" because not all tests run as I'm not set up for scala.js, and I am entirely unfamiliar with Scalatex.)
=> Added example of `NoCut` to documentation.

fastparse/shared/src/main/scala/fastparse/core/Parsing.scala, fastparse/shared/src/test/scala/fastparse/MiscTests.scala, readme/Readme.scalatex
fastparse.core.Result.Failure.formatParser() throws an UnsupportedOperationException on receiving an empty string as an input.
```
import fastparse.all._
val p = P("a")
p.parse("")
p.toString // throws
```
=> f.c.R.Failure.formatParser throws an exception on an empty input string

build.sbt
after https://github.com/lihaoyi/utest/pull/80 was merged,
fastparse was able to run, revealing that the same change
was needed her
=> fix dependency logic to work in Scala 2.12 community build

fastparse/shared/src/main/scala/fastparse/parsers/Combinators.scala, fastparse/shared/src/test/scala/fastparse/ParsingTests.scala, readme/Readme.scalatex
Please recheck, if last parameter `false` in
success(cfg.success, ev.result(ev.initial), index, List.empty[Parser[_]], false)
is ok!
Tests (plus additional tests for bugfix) run through.
=> #66 Bugfix.

fastparse/shared/src/test/scala/fastparse/MiscTests.scala, utils/shared/src/main/scala/fastparse/Utils.scala
This seems to make creation of the TrieNode much faster. It might fix #33
https://issues.scala-lang.org/browse/SI-4776
The TrieNode tree seems to be pretty fast once it is created. I compared it with my RadixTree https://github.com/rklaehn/radixtree , which is more optimised for compact storage of very large string sets, and it is doing quite well.
But creation of a TrieNode containing e.g. all words from http://www-01.sil.org/linguistics/wordlists/english/wordlist/wordsEn.txt would not even terminate.
=> Do not use lazy mapValues in TrieNode

fastparse/shared/src/main/scala/fastparse/WhitespaceApi.scala, fastparse/shared/src/test/scala/fastparse/GnipSubSyntaxTest.scala, readme/Readme.scalatex
Without the changes to **fastparse/shared/src/main/scala/fastparse/WhitespaceApi.scala** the added test will blow up the stack
=> expose #77 in test & fix by deduplicating traceParsers on every pass

README.md
My browser told be that the https connection is secure and I could not enter the documentation through that link, so I changed it to an http link that works nicely. I think having http instead of https for documentation is something most people can live with.
=> changed https to http in documentation link

byteparse/jvm/src/test/scala/byteparse/LargeBmpTests.scala, byteparse/shared/src/main/scala/byteparse/BmpParser.scala, byteparse/shared/src/main/scala/byteparse/classparse/ClassParser.scala, byteparse/shared/src/test/scala/byteparse/BmpTests.scala, cssparse/jvm/src/test/scala/cssparse/ProjectTests.scala, cssparse/shared/src/main/scala/cssparse/CssParser.scala, fastparse/shared/src/main/scala/fastparse/parsers/Terminals.scala, perftests/jvm/src/test/scala/perftests/ByteParse.scala, perftests/jvm/src/test/scala/perftests/ClassParse.scala, perftests/jvm/src/test/scala/perftests/CssParse.scala, perftests/jvm/src/test/scala/perftests/PythonParse.scala, perftests/shared/src/main/scala/perftests/Utils.scala
- Indent a bunch of parens the way everything else is indented
- Remove one dead statement
- change a bunch of `URL.getPath` to `URL.toURI.getPath` in order to make it work in folders with funny characters (e.g. spaces)
This should make the codebase more consistent and easier for me to work with...
Review by @vovapolu
=> First pass cleanup of GSOC code

fastparse/shared/src/main/scala/fastparse/WhitespaceApi.scala, fastparse/shared/src/main/scala/fastparse/parsers/Combinators.scala, fastparse/shared/src/test/scala/fastparse/iterator/IteratorTests.scala
In principle, we should be able to call `dropBuffer` immediately after the `lhs` of `lhs ~/ rhs` succeeds, as the cut occurs "in between" the `lhs` and `rhs`. 
Currently, we only call `dropBuffer` after the `rhs` succeeds, as when we're evaluating the "current" `lhs ~/ rhs`, after `lhs` succeeds we decide whether or not to `dropBuffer` based on the *previous* existence of cut, ignoring the fact that a cut had just occurred. Thus, if we had `a ~/ b ~ c`, we would call `dropBuffer` after `b` completes, while we really want it to occur after `a`.
This diff makes the consideration of `dropBuffer` also consider whether the "current" `CustomSequence`/iteration-in-`Sequence.Flat` just performed a cut. Thus, given `a ~/ b ~ c`, we now call `dropBuffer` immediately after `a`, in addition to after …
=> Improve aggressiveness of dropBuffer calls caused by cuts

fastparse/shared/src/main/scala/fastparse/Api.scala
So they can do their job but not leak out all over the place. This should reduce the amount of unnecessary things that get imported with `import fastparse.all._`
Review by @vovapolu
=> Privatize fastparse.Api's internal implicits

fastparse/shared/src/main/scala/fastparse/core/Parsing.scala, fastparse/shared/src/test/scala/fastparse/IteratorTests.scala, perftests/shared/src/main/scala/perftests/Utils.scala, utils/shared/src/main/scala/fastparse/ParserInput.scala, utils/shared/src/main/scala/fastparse/UberBuffer.scala
Looking up arrays are faster than vectors, copying arrays is faster than copying vectors, mutating arrays is faster than copy-and-updating vectors, and arrays take less memory to store than vectors
JProfiler was showing about 20-30% of time being spent inside various vector operations (lookup, copy-and-update, copy-to-array, ...) and this should make it disappear.
This implements a growable circular buffer to use as a queue, to replace the old var/Vector. As we write stuff to the buffer, we shift the `end` index to the right, wrapping around if there's empty space at the start of the `data` array. As we drop stuff, we simply shift the "start" index from to the right as well, also wrapping around. If the end index ever catches up with the start index, it means the buffer is full and we …
=> Speed up Iterator parsers by swapping out Vector for Circular Buffer

byteparse/jvm/src/test/scala/byteparse/LargeBmpIteratorTests.scala, byteparse/jvm/src/test/scala/byteparse/LargeBmpTests.scala, byteparse/shared/src/main/scala/byteparse/BmpParser.scala, byteparse/shared/src/main/scala/byteparse/classparse/ClassAttributes.scala, byteparse/shared/src/main/scala/byteparse/classparse/ClassParser.scala, byteparse/shared/src/main/scala/byteparse/classparse/CodeParser.scala, byteparse/shared/src/test/scala/byteparse/BmpTests.scala, byteparse/shared/src/test/scala/byteparse/ByteTests.scala, byteparse/shared/src/test/scala/byteparse/classparse/ClassTests.scala, byteparse/shared/src/test/scala/byteparse/classparse/TestUtils.scala, demo/src/main/scala/demo/DemoMain.scala, fastparse/shared/src/main/scala/fastparse/Api.scala, fastparse/shared/src/test/scala/fastparse/IteratorTests.scala, readme/Readme.scalatex
- Rename `allByte` to just `byte`, since that's what people would probably want most of the time
- Rename `emptyByteApi` to `byteNoApi`, for consistency with `fastparse.noApi`
- Rename `AnyWord` and `AnyDWord` to `Word16` and `Word32`, added `Word64`
- Rename `AnyWordI` and `AnyDWordI` to `Int16` and `Int32`, added `Int64`
- Added a new "basic" test to `IteratorTests.scala`, to use as an example in the docs
- Added the `pure-table` CSS class to our readme tables to make them look prettier
- Took a pass at editing and improving the readme
Review by @vovapolu
=> Readme improvements in preparation for 0.4.0

scalaparse/shared/src/main/scala/scalaparse/Types.scala
Hi, I asked about usage of `Pass ~` in scalaparse [on gitter](https://gitter.im/lihaoyi/fastparse?at=57a04f31c915a0e426b51aba) some days ago. So I was curious and tried to remove them. Here are those that don't fail tests. But there is still one left in `Types.scala` on the [line 33](https://github.com/laughedelic/fastparse/blob/bdade4a4c22de36264a9e076e402c517557a4087/scalaparse/shared/src/main/scala/scalaparse/Types.scala#L33) and one in `Scala.scala` on the [line 14](https://github.com/laughedelic/fastparse/blob/bdade4a4c22de36264a9e076e402c517557a4087/scalaparse/shared/src/main/scala/scalaparse/Scala.scala#L14). If I remove them some tests fail. 
I don't understand why they were there in the first place and why those two are essential. My guess would be that these two interact somehow …
=> Strange usage of Pass in scalaparse

classparse/shared/src/main/scala/classparse/ClassAttributes.scala, classparse/shared/src/main/scala/classparse/ClassParse.scala, classparse/shared/src/main/scala/classparse/CodeParser.scala, classparse/shared/src/test/scala/classparse/ClassTests.scala, fastparse/shared/src/main/scala/fastparse/Api.scala, fastparse/shared/src/test/scala/fastparse/BmpTests.scala, fastparse/shared/src/test/scala/fastparse/ByteTests.scala, fastparse/shared/src/test/scala/fastparse/ExampleTests.scala, project/build.sbt, readme/Readme.scalatex
- Rename `strToBytes` -> `hexBytes`, to make it clear what kind of st…ring it is
- `BytesParser` -> `HexBytesParser`
- Added forwarder values for `LE` and `BE` inside `fastparse.bytes` so you don't need to import them separately
- Converted a few `.flatMap`s to use `for`-comprehensions since I think those are nicer to read. Added some docs to mention that you can use both `for`-comprehensions and explicit `flatMap`s
- Added a new `fastparse.bytes` example: a UDP packet parser, which I made into the top-example for the`Byte Parsers` docs
- Moved `ScalaParse` doc under the `Example Parsers`, since top-level was getting a bit crowded
- Added a new documentation section under `Internals`, to mention how two-way round-trip parse -> re-serialization isn't supported by FastParse.
- Flipped the …
=> Another pass of code/docs polish work for byte-parser API

fastparse/shared/src/main/scala/fastparse/core/Parsing.scala, fastparse/shared/src/test/scala/fastparse/ExampleTests.scala, fastparse/shared/src/test/scala/fastparse/ParsingTests.scala, readme/ApiHighlights.scalatex
This should mostly resolve #34 as users would not have to pattern match on a the Parsed result type
=> Added fold method to Parsed ADT

fastparse/shared/src/main/scala/fastparse/core/Parsing.scala, fastparse/shared/src/main/scala/fastparse/parsers/Combinators.scala, fastparse/shared/src/main/scala/fastparse/parsers/Transformers.scala, fastparse/shared/src/test/scala/fastparse/ParsingTests.scala
We were not properly propagating the `cut`s in the LHS of `flatMap`s; that meant that if there was a `cut` inside the left hand parser, it doesn't take effect if something fails in the RHS of the `flatMap` call, or if the `flatMap` succeeds but something fails later.
Also makes `!` and `&` negative/positive lookaheads behave as `NoCut`s: the whole point of those operators is to backtrack, so there isn't any conceivable use-case where someone would want to use them and have a cut disable-backtracking/drop-buffer when inside one of these operators.
Also properly propagates cuts in `foo.filter(pred)` when `foo` passes but `pred` fails.
Found these when investigating the build failure in https://github.com/lihaoyi/fastparse/pull/122. Possibly not the only issue, but it's something. This …
=> Properly handle cuts in LHS of flatMap calls and Not/Lookahead/Filter

build.sbt, classparse/jvm/src/test/scala/classparse/ProjectTests.scala, classparse/shared/src/main/scala/classparse/ClassAttributes.scala, classparse/shared/src/main/scala/classparse/ClassParse.scala, classparse/shared/src/main/scala/classparse/CodeParser.scala, classparse/shared/src/test/scala/classparse/ClassTests.scala, classparse/shared/src/test/scala/classparse/TestUtils.scala, demo/src/main/scala/demo/DemoMain.scala, fastparse/jvm/src/test/scala/fastparse/LargeBmpIteratorTests.scala, fastparse/jvm/src/test/scala/fastparse/LargeBmpTests.scala, fastparse/jvm/src/test/scala/fastparse/MidiTests.scala, fastparse/shared/src/main/scala/fastparse/Api.scala, fastparse/shared/src/main/scala/fastparse/ByteUtils.scala, fastparse/shared/src/test/scala/fastparse/BmpTests.scala, fastparse/shared/src/test/scala/fastparse/ByteTests.scala, fastparse/shared/src/test/scala/fastparse/MidiParse.scala, perftests/jvm/src/test/scala/perftests/binary/BmpParse.scala, perftests/jvm/src/test/scala/perftests/binary/ClassParse.scala, perftests/jvm/src/test/scala/perftests/binary/MidiParse.scala, readme/ByteParsers.scalatex, utils/shared/src/main/scala/fastparse/ElemTypeFormatter.scala
This is an experiment to see what it will look like if we use `ByteVector` instead of `Array[Byte]`. Major changes:
- `hexBytes` is gone, replaced by Scodec's `hex""` interpolator
- FastParse now depends on `scodec-bits`.
- `scodec.bits.ByteVector` is now aliased to `fastparse.byte.Bytes`, usually used as just `Bytes`, for conciseness
- Implicit conversion between `Array[Byte] => Parser[Unit, Byte, Array[Byte]]` is now gone, as if we make it `Bytes => Parser[Unit, Byte, Bytes]`, then using the `|` operator on two `Bytes` values within a parser behaves surprisingly: it bit-wise `|`s the two `Bytes` values together rather than constructing a parser that can parse either.
- `BS` now constructs `Parser[Unit]` instead of constructing `Array[Byte]` and relying on the implicit to convert it to a …
=> Convert fastparse.byte to use scodec.bits.ByteVector instead of Array[Byte]

fastparse/shared/src/main/scala/fastparse/Api.scala, fastparse/shared/src/main/scala/fastparse/parsers/Intrinsics.scala, fastparse/shared/src/test/scala/fastparse/MiscTests.scala, fastparse/shared/src/test/scala/fastparse/ParsingTests.scala, utils/shared/src/main/scala/fastparse/Utils.scala
We're replacing the parser combinators library with fastparse and one thing we're working around is parsing for a set of case insensitive strings. This PR adds that feature with a small change to the StringIn parser, and adds a couple tests.
=> Added a StringInIgnoreCase parser

pythonparse/shared/src/main/scala/pythonparse/Ast.scala, pythonparse/shared/src/main/scala/pythonparse/Expressions.scala, pythonparse/shared/src/main/scala/pythonparse/Lexical.scala, pythonparse/shared/src/test/scala/pythonparse/RegressionTests.scala, pythonparse/shared/src/test/scala/pythonparse/UnitTests.scala
This PR allows `pythonparse` to recognize two previously-ignored constructs:
- Negative number literals.
- Unary operations `UAdd`, `USub`, and `Invert`.
Previously, `pythonparse` discarded these operators, rather than surfacing them as part of the constructed `Ast`. The logic linked below was responsible for discarding unary operators:
https://github.com/lihaoyi/fastparse/compare/master...jeremydhoon:jhoon-unaryop-invert?expand=1#diff-7fe7f240cf772c974bc24a8ecc6bd120L91
To capture these operators properly, the PR makes three changes:
- When parsing numbers, we capture a preceding sign operator and use it in computing the number's Scala value.
- When parsing `factor`s, we capture preceding unary operators, wrapping the subsequent expression with a `UnaryOp` if found.
- Before attempting …
=> pythonparse: Parse unary operations and negative numbers

pythonparse/shared/src/main/scala/pythonparse/Expressions.scala, pythonparse/shared/src/test/scala/pythonparse/UnitTests.scala
When parsing an expression such as `(a + b) * (c - d)`, the parenthesized terms should be treated as scalar expressions. The current behavior in `pythonparse` is to treat these terms as single-item tuples.
The PR adds a different parser for the contents of tuples, which ensure the presence of at least one `test` followed by a comma in order to consider the expression a tuple. To capture the scalar expression case, the PR adds a case for `test` to the parser for parenthesized terms under `atom`.
The PR adds two brief unit test cases. I verified that the expected parses match the results produced by `ast.dump(ast.parse('...'))` in Python.
=> pythonparse: Do not parse parenthetical expressions as single-item tuples

scalaparse/shared/src/main/scala/scalaparse/Xml.scala, scalaparse/shared/src/test/scala/scalaparse/unit/FailureTests.scala, scalaparse/shared/src/test/scala/scalaparse/unit/SuccessTests.scala
The actual xml parser does not match the one from scalac. This parser is based on the one from [scalac](https://github.com/scala/scala/blob/2.12.x/src/compiler/scala/tools/nsc/ast/parser/MarkupParsers.scala).
=> Rewrite the XML parser based on the scalac one

.travis.yml, build.sbt, project/build.sbt
Opening this PR just to show progress, currently waiting for new release of scodec bits and Scala Native to fix remaining issues. Tests pass for fastparse/scalaparse/cssparse when using a local publish of scala native with https://github.com/scala-native/scala-native/pull/902.
=> Port to Scala Native

README.md, build.sbt, project/Constants.scala, project/build.properties, project/build.sbt, readme/Changelog.scalatex
`+modules/publishSigned` will no longer work since native projects only cross-build against 2.11. sbt-doge solves this by making `very publishSigned` only run publishSigned for the defined crossScalaVersions in each project. However, the `modules` aggregate was messing up something so that the native modules were still being built against 2.10 with `very compile`. Removing `modules` fixed the problem.
While trying to debug the problems, I some changes to clean up build.sbt to better understand what was happening.
=> Reorganize build for easier cross-publish

build.sbt, scalaparse/shared/src/test/scala/scalaparse/TestUtil.scala
this is needed for the Scala community build; fansi requires the
latest utest now, so anything else using utest must be
source-compatible with the latest utest too
=> upgrade to latest utest (0.5.3)

scalaparse/jvm/src/test/scala/scalaparse/ProjectTests.scala
I noticed that fastparse/target/repos is a disk hog in the community build.
This commit changes the checkout of third party repos by test cases to use a shallow clone,
as is already done in classparse/jvm/src/test/scala/classparse/ProjectTests.scala
References https://github.com/scala/community-builds/issues/617
=> Use a shallow clone in scalaparse ProjectTests

fastparse/shared/src/main/scala/fastparse/Api.scala, fastparse/shared/src/main/scala/fastparse/parsers/Combinators.scala, fastparse/shared/src/test/scala/fastparse/ExampleTests.scala
Adds support for `sequence`. It allows multiple parsers (with same result type) to be combined with possibly a(n ignored) separator parser, just like in `rep`.
Feel free to suggest changes.
=> Seq sequence support

readme/ExampleParsers.scalatex
It's not clear from the current documentation how to sometimes ignore the whitespace. Stumbled across these operators in #174.
=> Add note about non-whitespace consuming operators

fastparse/src/fastparse/package.scala
This PR fixes the Scaladoc of the `~~` operator under `EagerOps`, since it runs two parsers without whitespace in between.
=> Fix Scaladoc of `~~` operator

fastparse/test/src/fastparse/ExampleTests.scala, readme/WritingParsers.scalatex
Examples and docs should compile according to travis. I don't currently have Mill set up to test locally, but as far as I can tell things are working well.
=> Add Documentation for Higher Order Parsers

.travis.yml
The stable release for 2.1.1 timed out on Travis due to the maximum 50
minute limit. This commit splits the release stage into three parallel
jobs to publish 2.11, 2.12 and 2.13 separately. This will hopefully
overcome the timeout limit on Travis CI.
Review @alexarchambault
=> Split release stage into parallel jobs.

fastparse/test/src/fastparse/ExampleTests.scala
- change a use of `__` to `_`
- add one more example
=> improve examples for `Positive Lookahead`

build.sc
Sadly I couldn't find a way to avoid generating a proper docJar for Scala Native `0.4.0-M2` (since it works correctly) because code like this:
```scala
if(scalaNativeVersion == "0.3.9") {
val outDir = T.dest
os.makeDir.all(outDir / 'javadoc)
createJar(Agg(outDir / 'javadoc))(outDir)
} else super.docJar()
```
tries to run `super.docJar()` regardless of the result of the if expression.
If you have a solution to this problem I can change that.
Otherwise we can live with an empty docJar for Scala Native 😃
=> Fix docJar for Scala Native 0.3.9

build.sc
Thanks to @lefou's suggestion I can reactivate `docJar` for Scala Native 0.4.0-M2.
=> Activate docJar generation for Scala Native 0.4.0-M2

build.sc
Sorry, I overlooked another detail and "fastparse-native_native0.4.0-M2" got published 🙈
=> Remove "-native" suffix from Scala Native artifact name

cssparse/src/cssparse/CssParser.scala, cssparse/test/src/cssparse/CssTests.scala
fixes https://github.com/com-lihaoyi/fastparse/issues/255
Enable backtracking on comments, otherwise the parser will error when the comment is last line in a block.
=> fix css comment bug. 

LICENSE
- Copy text from README.md.
- This makes it easier for tools (including GitHub itself) to figure out
what the license of this package is.
=> Add an explicit LICENSE file.

fastparse/src/fastparse/Parsed.scala
This makes code like the following compile without an exhaustiveness warning:
```scala
parse(...) match {
case Failure(err, index, extra) =>
...
case Success(p, index) =>
...
}
```
Instead, one currently has to write:
```scala
parse(...) match {
case f: Failure =>
val Failure(err, index, extra) = f
...
case Success(p, index) =>
...
}
```
=> Make Failure extractor exhaustive

.gitignore, fastparse/src/fastparse/internal/MacroImpls.scala, fastparse/src/fastparse/package.scala, fastparse/test/src/fastparse/ExampleTests.scala
Transforms the result of this parser using the given partial function, failing the parse if the partial function is not defined on the result of the current parser. This is eqivalent to `.filter(f.isDefinedAt).map(f.apply)`.
=> Implement P.collect

build.sc, fastparse/src-2/fastparse/internal/MacroImpls.scala, fastparse/src-2/fastparse/package.scala, fastparse/src-3/fastparse/internal/MacroInlineImpls.scala, fastparse/src-3/fastparse/internal/MacroRepImpls.scala, fastparse/src-3/fastparse/package.scala, fastparse/src/fastparse/Whitespace.scala, fastparse/src/fastparse/internal/RepImpls.scala, fastparse/src/fastparse/internal/Util.scala, fastparse/test/src-2.12+/fastparse/CustomWhitespaceMathTests.scala, fastparse/test/src-2.12+/fastparse/IteratorTests.scala, fastparse/test/src/fastparse/ParsingTests.scala, fastparse/test/src/fastparse/WhitespaceTests.scala, pythonparse/src/pythonparse/Expressions.scala, pythonparse/src/pythonparse/Statements.scala
Fixes https://github.com/com-lihaoyi/fastparse/issues/261, which is caused by the whitespace `P[_] => P[Unit]` implicits firing as implicit conversions rather than the implicit parameters they were originally intended to be. Since whitespace is meant to ignore failures, this caused failures caused by the `Fail.! : P[String]` to be ignored when implicitly converted to `P[Unit]`
The fix is to create a proper `Whitespace` trait to inherit from. 
Note that this is a binary incompatible change. It's stacked on top of https://github.com/com-lihaoyi/fastparse/pull/271 for convenience, but should probably land separately after. The relevant changes are in this commit https://github.com/com-lihaoyi/fastparse/pull/272/commits/d87ab6d9de062ec1e0bbf897643cefef7cd03338 if anyone wants to look.
Note …
=> Make Whitespace a proper trait rather than function to avoid unwanted implicit conversions

build.sc
This makes source maps to point to Github instead of a non-existing local source file (with the path from the CI machine)
=> Add sourceMap mapping to Scala.js

fastparse/src/fastparse/SharedPackageDefs.scala, fastparse/test/src/fastparse/ParsingTests.scala, readme/Changelog.scalatex, scalaparse/test/src/scalaparse/unit/FailureTests.scala
We need to manually backtrack any terminals that are seen in a `.opaque` parser, since it's meant to be opaque
=> Fix handling of terminals in opaque

fastparse/src/fastparse/internal/Util.scala, fastparse/test/src/fastparse/UtilTests.scala
Previous implementation of `lineNumberLookup` only worked for single `\n` or `\r` newlines. This PR fixes it so it also works for `\n\r` or `\r\n` newlines and adds some basic tests
=> Fix line and column number reporting for Windows newlines

README.md, build.sc, fastparse/src/fastparse/SharedPackageDefs.scala, fastparse/test/src/fastparse/ExampleTests.scala
Simply replace '"fail"' with 'msg' to use the provided custom error message
Additionally:
* Add 3.3.1 as a cross-build target
* Put quotes in the "Common Commands" section of the README so that the commands are directly 
copyable for Zsh, Csh, Bash, etc. Should work on Windows too
=> Implement fix for #296

build.sc, cssparse/src/cssparse/CssParser.scala, cssparse/test/src/cssparse/CssTests.scala, fastparse/src-2.12/fastparse/internal/NoWarn.scala, fastparse/src-2/fastparse/internal/MacroImpls.scala, fastparse/src-2/fastparse/internal/MacroRepImpls.scala, fastparse/src-2/fastparse/package.scala, fastparse/src-3/fastparse/internal/MacroInlineImpls.scala, fastparse/src/fastparse/ParsingRun.scala, fastparse/src/fastparse/Whitespace.scala, fastparse/test/src/fastparse/ExampleTests.scala, pythonparse/src/pythonparse/Statements.scala
Motivation:
Enable unused lint for fastparse
Modification:
Some straightforward changing to make compiler happy
Result:
less warning when comping.
=> chore: Enable lint and fix some unused warning.
